name: ci
on: [push]
jobs:
  tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Component tests
        uses: cypress-io/github-action@v4
        with:
          # we have already installed everything
          component: true

      # https://github.com/cypress-io/github-action
      - name: Run E2E tests
        uses: cypress-io/github-action@v4
        with:
          install: false
          start: npm start
          wait-on: 'http://localhost:3000'

      
